services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-react
    restart: unless-stopped
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat-router.rule=Host(`chatreact.vps.malejka.lowicz.pl`)"
      - "traefik.http.routers.chat-router.entrypoints=websecure"
      - "traefik.http.routers.chat-router.tls.certresolver=myresolver"
      - "traefik.http.services.chat-service.loadbalancer.server.port=80"

networks:
  proxy:
    external: true